/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as WebsiteWartungLeverkusenRouteImport } from './routes/website-wartung-leverkusen'
import { Route as WebsiteFuerHausverwaltungLeverkusenRouteImport } from './routes/website-fuer-hausverwaltung-leverkusen'
import { Route as WebsiteFuerHandwerkerLeverkusenRouteImport } from './routes/website-fuer-handwerker-leverkusen'
import { Route as WebsiteFuerAnwaltskanzleiLeverkusenRouteImport } from './routes/website-fuer-anwaltskanzlei-leverkusen'
import { Route as WebdesignLeverkusenRouteImport } from './routes/webdesign-leverkusen'
import { Route as WartungsvertragItRouteImport } from './routes/wartungsvertrag-it'
import { Route as UkRouteImport } from './routes/uk'
import { Route as UaRouteImport } from './routes/ua'
import { Route as RuRouteImport } from './routes/ru'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as ItSupportLeverkusenRouteImport } from './routes/it-support-leverkusen'
import { Route as ItServiceLeverkusenRouteImport } from './routes/it-service-leverkusen'
import { Route as ItBetreuungKleineUnternehmenRouteImport } from './routes/it-betreuung-kleine-unternehmen'
import { Route as ItBeratungLeverkusenRouteImport } from './routes/it-beratung-leverkusen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenzenWupperstahlRouteImport } from './routes/referenzen_.wupperstahl'
import { Route as ReferenzenHausverwaltungFrankRouteImport } from './routes/referenzen_.hausverwaltung-frank'
import { Route as ReferenzenErbrechtLeverkusenRouteImport } from './routes/referenzen_.erbrecht-leverkusen'

const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteWartungLeverkusenRoute =
  WebsiteWartungLeverkusenRouteImport.update({
    id: '/website-wartung-leverkusen',
    path: '/website-wartung-leverkusen',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteFuerHausverwaltungLeverkusenRoute =
  WebsiteFuerHausverwaltungLeverkusenRouteImport.update({
    id: '/website-fuer-hausverwaltung-leverkusen',
    path: '/website-fuer-hausverwaltung-leverkusen',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteFuerHandwerkerLeverkusenRoute =
  WebsiteFuerHandwerkerLeverkusenRouteImport.update({
    id: '/website-fuer-handwerker-leverkusen',
    path: '/website-fuer-handwerker-leverkusen',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteFuerAnwaltskanzleiLeverkusenRoute =
  WebsiteFuerAnwaltskanzleiLeverkusenRouteImport.update({
    id: '/website-fuer-anwaltskanzlei-leverkusen',
    path: '/website-fuer-anwaltskanzlei-leverkusen',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebdesignLeverkusenRoute = WebdesignLeverkusenRouteImport.update({
  id: '/webdesign-leverkusen',
  path: '/webdesign-leverkusen',
  getParentRoute: () => rootRouteImport,
} as any)
const WartungsvertragItRoute = WartungsvertragItRouteImport.update({
  id: '/wartungsvertrag-it',
  path: '/wartungsvertrag-it',
  getParentRoute: () => rootRouteImport,
} as any)
const UkRoute = UkRouteImport.update({
  id: '/uk',
  path: '/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const UaRoute = UaRouteImport.update({
  id: '/ua',
  path: '/ua',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const ItSupportLeverkusenRoute = ItSupportLeverkusenRouteImport.update({
  id: '/it-support-leverkusen',
  path: '/it-support-leverkusen',
  getParentRoute: () => rootRouteImport,
} as any)
const ItServiceLeverkusenRoute = ItServiceLeverkusenRouteImport.update({
  id: '/it-service-leverkusen',
  path: '/it-service-leverkusen',
  getParentRoute: () => rootRouteImport,
} as any)
const ItBetreuungKleineUnternehmenRoute =
  ItBetreuungKleineUnternehmenRouteImport.update({
    id: '/it-betreuung-kleine-unternehmen',
    path: '/it-betreuung-kleine-unternehmen',
    getParentRoute: () => rootRouteImport,
  } as any)
const ItBeratungLeverkusenRoute = ItBeratungLeverkusenRouteImport.update({
  id: '/it-beratung-leverkusen',
  path: '/it-beratung-leverkusen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenWupperstahlRoute = ReferenzenWupperstahlRouteImport.update({
  id: '/referenzen_/wupperstahl',
  path: '/referenzen/wupperstahl',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenHausverwaltungFrankRoute =
  ReferenzenHausverwaltungFrankRouteImport.update({
    id: '/referenzen_/hausverwaltung-frank',
    path: '/referenzen/hausverwaltung-frank',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenzenErbrechtLeverkusenRoute =
  ReferenzenErbrechtLeverkusenRouteImport.update({
    id: '/referenzen_/erbrecht-leverkusen',
    path: '/referenzen/erbrecht-leverkusen',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/it-beratung-leverkusen': typeof ItBeratungLeverkusenRoute
  '/it-betreuung-kleine-unternehmen': typeof ItBetreuungKleineUnternehmenRoute
  '/it-service-leverkusen': typeof ItServiceLeverkusenRoute
  '/it-support-leverkusen': typeof ItSupportLeverkusenRoute
  '/referenzen': typeof ReferenzenRoute
  '/ru': typeof RuRoute
  '/ua': typeof UaRoute
  '/uk': typeof UkRoute
  '/wartungsvertrag-it': typeof WartungsvertragItRoute
  '/webdesign-leverkusen': typeof WebdesignLeverkusenRoute
  '/website-fuer-anwaltskanzlei-leverkusen': typeof WebsiteFuerAnwaltskanzleiLeverkusenRoute
  '/website-fuer-handwerker-leverkusen': typeof WebsiteFuerHandwerkerLeverkusenRoute
  '/website-fuer-hausverwaltung-leverkusen': typeof WebsiteFuerHausverwaltungLeverkusenRoute
  '/website-wartung-leverkusen': typeof WebsiteWartungLeverkusenRoute
  '/widerruf': typeof WiderrufRoute
  '/referenzen/erbrecht-leverkusen': typeof ReferenzenErbrechtLeverkusenRoute
  '/referenzen/hausverwaltung-frank': typeof ReferenzenHausverwaltungFrankRoute
  '/referenzen/wupperstahl': typeof ReferenzenWupperstahlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/it-beratung-leverkusen': typeof ItBeratungLeverkusenRoute
  '/it-betreuung-kleine-unternehmen': typeof ItBetreuungKleineUnternehmenRoute
  '/it-service-leverkusen': typeof ItServiceLeverkusenRoute
  '/it-support-leverkusen': typeof ItSupportLeverkusenRoute
  '/referenzen': typeof ReferenzenRoute
  '/ru': typeof RuRoute
  '/ua': typeof UaRoute
  '/uk': typeof UkRoute
  '/wartungsvertrag-it': typeof WartungsvertragItRoute
  '/webdesign-leverkusen': typeof WebdesignLeverkusenRoute
  '/website-fuer-anwaltskanzlei-leverkusen': typeof WebsiteFuerAnwaltskanzleiLeverkusenRoute
  '/website-fuer-handwerker-leverkusen': typeof WebsiteFuerHandwerkerLeverkusenRoute
  '/website-fuer-hausverwaltung-leverkusen': typeof WebsiteFuerHausverwaltungLeverkusenRoute
  '/website-wartung-leverkusen': typeof WebsiteWartungLeverkusenRoute
  '/widerruf': typeof WiderrufRoute
  '/referenzen/erbrecht-leverkusen': typeof ReferenzenErbrechtLeverkusenRoute
  '/referenzen/hausverwaltung-frank': typeof ReferenzenHausverwaltungFrankRoute
  '/referenzen/wupperstahl': typeof ReferenzenWupperstahlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/it-beratung-leverkusen': typeof ItBeratungLeverkusenRoute
  '/it-betreuung-kleine-unternehmen': typeof ItBetreuungKleineUnternehmenRoute
  '/it-service-leverkusen': typeof ItServiceLeverkusenRoute
  '/it-support-leverkusen': typeof ItSupportLeverkusenRoute
  '/referenzen': typeof ReferenzenRoute
  '/ru': typeof RuRoute
  '/ua': typeof UaRoute
  '/uk': typeof UkRoute
  '/wartungsvertrag-it': typeof WartungsvertragItRoute
  '/webdesign-leverkusen': typeof WebdesignLeverkusenRoute
  '/website-fuer-anwaltskanzlei-leverkusen': typeof WebsiteFuerAnwaltskanzleiLeverkusenRoute
  '/website-fuer-handwerker-leverkusen': typeof WebsiteFuerHandwerkerLeverkusenRoute
  '/website-fuer-hausverwaltung-leverkusen': typeof WebsiteFuerHausverwaltungLeverkusenRoute
  '/website-wartung-leverkusen': typeof WebsiteWartungLeverkusenRoute
  '/widerruf': typeof WiderrufRoute
  '/referenzen_/erbrecht-leverkusen': typeof ReferenzenErbrechtLeverkusenRoute
  '/referenzen_/hausverwaltung-frank': typeof ReferenzenHausverwaltungFrankRoute
  '/referenzen_/wupperstahl': typeof ReferenzenWupperstahlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/it-beratung-leverkusen'
    | '/it-betreuung-kleine-unternehmen'
    | '/it-service-leverkusen'
    | '/it-support-leverkusen'
    | '/referenzen'
    | '/ru'
    | '/ua'
    | '/uk'
    | '/wartungsvertrag-it'
    | '/webdesign-leverkusen'
    | '/website-fuer-anwaltskanzlei-leverkusen'
    | '/website-fuer-handwerker-leverkusen'
    | '/website-fuer-hausverwaltung-leverkusen'
    | '/website-wartung-leverkusen'
    | '/widerruf'
    | '/referenzen/erbrecht-leverkusen'
    | '/referenzen/hausverwaltung-frank'
    | '/referenzen/wupperstahl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/it-beratung-leverkusen'
    | '/it-betreuung-kleine-unternehmen'
    | '/it-service-leverkusen'
    | '/it-support-leverkusen'
    | '/referenzen'
    | '/ru'
    | '/ua'
    | '/uk'
    | '/wartungsvertrag-it'
    | '/webdesign-leverkusen'
    | '/website-fuer-anwaltskanzlei-leverkusen'
    | '/website-fuer-handwerker-leverkusen'
    | '/website-fuer-hausverwaltung-leverkusen'
    | '/website-wartung-leverkusen'
    | '/widerruf'
    | '/referenzen/erbrecht-leverkusen'
    | '/referenzen/hausverwaltung-frank'
    | '/referenzen/wupperstahl'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/it-beratung-leverkusen'
    | '/it-betreuung-kleine-unternehmen'
    | '/it-service-leverkusen'
    | '/it-support-leverkusen'
    | '/referenzen'
    | '/ru'
    | '/ua'
    | '/uk'
    | '/wartungsvertrag-it'
    | '/webdesign-leverkusen'
    | '/website-fuer-anwaltskanzlei-leverkusen'
    | '/website-fuer-handwerker-leverkusen'
    | '/website-fuer-hausverwaltung-leverkusen'
    | '/website-wartung-leverkusen'
    | '/widerruf'
    | '/referenzen_/erbrecht-leverkusen'
    | '/referenzen_/hausverwaltung-frank'
    | '/referenzen_/wupperstahl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  ItBeratungLeverkusenRoute: typeof ItBeratungLeverkusenRoute
  ItBetreuungKleineUnternehmenRoute: typeof ItBetreuungKleineUnternehmenRoute
  ItServiceLeverkusenRoute: typeof ItServiceLeverkusenRoute
  ItSupportLeverkusenRoute: typeof ItSupportLeverkusenRoute
  ReferenzenRoute: typeof ReferenzenRoute
  RuRoute: typeof RuRoute
  UaRoute: typeof UaRoute
  UkRoute: typeof UkRoute
  WartungsvertragItRoute: typeof WartungsvertragItRoute
  WebdesignLeverkusenRoute: typeof WebdesignLeverkusenRoute
  WebsiteFuerAnwaltskanzleiLeverkusenRoute: typeof WebsiteFuerAnwaltskanzleiLeverkusenRoute
  WebsiteFuerHandwerkerLeverkusenRoute: typeof WebsiteFuerHandwerkerLeverkusenRoute
  WebsiteFuerHausverwaltungLeverkusenRoute: typeof WebsiteFuerHausverwaltungLeverkusenRoute
  WebsiteWartungLeverkusenRoute: typeof WebsiteWartungLeverkusenRoute
  WiderrufRoute: typeof WiderrufRoute
  ReferenzenErbrechtLeverkusenRoute: typeof ReferenzenErbrechtLeverkusenRoute
  ReferenzenHausverwaltungFrankRoute: typeof ReferenzenHausverwaltungFrankRoute
  ReferenzenWupperstahlRoute: typeof ReferenzenWupperstahlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-wartung-leverkusen': {
      id: '/website-wartung-leverkusen'
      path: '/website-wartung-leverkusen'
      fullPath: '/website-wartung-leverkusen'
      preLoaderRoute: typeof WebsiteWartungLeverkusenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-fuer-hausverwaltung-leverkusen': {
      id: '/website-fuer-hausverwaltung-leverkusen'
      path: '/website-fuer-hausverwaltung-leverkusen'
      fullPath: '/website-fuer-hausverwaltung-leverkusen'
      preLoaderRoute: typeof WebsiteFuerHausverwaltungLeverkusenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-fuer-handwerker-leverkusen': {
      id: '/website-fuer-handwerker-leverkusen'
      path: '/website-fuer-handwerker-leverkusen'
      fullPath: '/website-fuer-handwerker-leverkusen'
      preLoaderRoute: typeof WebsiteFuerHandwerkerLeverkusenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-fuer-anwaltskanzlei-leverkusen': {
      id: '/website-fuer-anwaltskanzlei-leverkusen'
      path: '/website-fuer-anwaltskanzlei-leverkusen'
      fullPath: '/website-fuer-anwaltskanzlei-leverkusen'
      preLoaderRoute: typeof WebsiteFuerAnwaltskanzleiLeverkusenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webdesign-leverkusen': {
      id: '/webdesign-leverkusen'
      path: '/webdesign-leverkusen'
      fullPath: '/webdesign-leverkusen'
      preLoaderRoute: typeof WebdesignLeverkusenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wartungsvertrag-it': {
      id: '/wartungsvertrag-it'
      path: '/wartungsvertrag-it'
      fullPath: '/wartungsvertrag-it'
      preLoaderRoute: typeof WartungsvertragItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk': {
      id: '/uk'
      path: '/uk'
      fullPath: '/uk'
      preLoaderRoute: typeof UkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ua': {
      id: '/ua'
      path: '/ua'
      fullPath: '/ua'
      preLoaderRoute: typeof UaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-support-leverkusen': {
      id: '/it-support-leverkusen'
      path: '/it-support-leverkusen'
      fullPath: '/it-support-leverkusen'
      preLoaderRoute: typeof ItSupportLeverkusenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-service-leverkusen': {
      id: '/it-service-leverkusen'
      path: '/it-service-leverkusen'
      fullPath: '/it-service-leverkusen'
      preLoaderRoute: typeof ItServiceLeverkusenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-betreuung-kleine-unternehmen': {
      id: '/it-betreuung-kleine-unternehmen'
      path: '/it-betreuung-kleine-unternehmen'
      fullPath: '/it-betreuung-kleine-unternehmen'
      preLoaderRoute: typeof ItBetreuungKleineUnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-beratung-leverkusen': {
      id: '/it-beratung-leverkusen'
      path: '/it-beratung-leverkusen'
      fullPath: '/it-beratung-leverkusen'
      preLoaderRoute: typeof ItBeratungLeverkusenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen_/wupperstahl': {
      id: '/referenzen_/wupperstahl'
      path: '/referenzen/wupperstahl'
      fullPath: '/referenzen/wupperstahl'
      preLoaderRoute: typeof ReferenzenWupperstahlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen_/hausverwaltung-frank': {
      id: '/referenzen_/hausverwaltung-frank'
      path: '/referenzen/hausverwaltung-frank'
      fullPath: '/referenzen/hausverwaltung-frank'
      preLoaderRoute: typeof ReferenzenHausverwaltungFrankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen_/erbrecht-leverkusen': {
      id: '/referenzen_/erbrecht-leverkusen'
      path: '/referenzen/erbrecht-leverkusen'
      fullPath: '/referenzen/erbrecht-leverkusen'
      preLoaderRoute: typeof ReferenzenErbrechtLeverkusenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  ItBeratungLeverkusenRoute: ItBeratungLeverkusenRoute,
  ItBetreuungKleineUnternehmenRoute: ItBetreuungKleineUnternehmenRoute,
  ItServiceLeverkusenRoute: ItServiceLeverkusenRoute,
  ItSupportLeverkusenRoute: ItSupportLeverkusenRoute,
  ReferenzenRoute: ReferenzenRoute,
  RuRoute: RuRoute,
  UaRoute: UaRoute,
  UkRoute: UkRoute,
  WartungsvertragItRoute: WartungsvertragItRoute,
  WebdesignLeverkusenRoute: WebdesignLeverkusenRoute,
  WebsiteFuerAnwaltskanzleiLeverkusenRoute:
    WebsiteFuerAnwaltskanzleiLeverkusenRoute,
  WebsiteFuerHandwerkerLeverkusenRoute: WebsiteFuerHandwerkerLeverkusenRoute,
  WebsiteFuerHausverwaltungLeverkusenRoute:
    WebsiteFuerHausverwaltungLeverkusenRoute,
  WebsiteWartungLeverkusenRoute: WebsiteWartungLeverkusenRoute,
  WiderrufRoute: WiderrufRoute,
  ReferenzenErbrechtLeverkusenRoute: ReferenzenErbrechtLeverkusenRoute,
  ReferenzenHausverwaltungFrankRoute: ReferenzenHausverwaltungFrankRoute,
  ReferenzenWupperstahlRoute: ReferenzenWupperstahlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
