/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as UkRouteImport } from './routes/uk'
import { Route as UaRouteImport } from './routes/ua'
import { Route as RuRouteImport } from './routes/ru'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'

const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const UkRoute = UkRouteImport.update({
  id: '/uk',
  path: '/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const UaRoute = UaRouteImport.update({
  id: '/ua',
  path: '/ua',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/ru': typeof RuRoute
  '/ua': typeof UaRoute
  '/uk': typeof UkRoute
  '/widerruf': typeof WiderrufRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/ru': typeof RuRoute
  '/ua': typeof UaRoute
  '/uk': typeof UkRoute
  '/widerruf': typeof WiderrufRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/ru': typeof RuRoute
  '/ua': typeof UaRoute
  '/uk': typeof UkRoute
  '/widerruf': typeof WiderrufRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/ru'
    | '/ua'
    | '/uk'
    | '/widerruf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/datenschutz' | '/impressum' | '/ru' | '/ua' | '/uk' | '/widerruf'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/ru'
    | '/ua'
    | '/uk'
    | '/widerruf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  RuRoute: typeof RuRoute
  UaRoute: typeof UaRoute
  UkRoute: typeof UkRoute
  WiderrufRoute: typeof WiderrufRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk': {
      id: '/uk'
      path: '/uk'
      fullPath: '/uk'
      preLoaderRoute: typeof UkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ua': {
      id: '/ua'
      path: '/ua'
      fullPath: '/ua'
      preLoaderRoute: typeof UaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  RuRoute: RuRoute,
  UaRoute: UaRoute,
  UkRoute: UkRoute,
  WiderrufRoute: WiderrufRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
